#!/bin/bash

source "${CONTAINER_REPO_DIR}.container/lib/onbb_utils.sh"

# Hide stdout, keep stderr, wait, output result
onbb_wait_until_ready 120 >/dev/null || (onbb_echo_result_of_start_failed ${CONTAINER_REPO_DIR}/nodebb/logs/output.log && exit 1) || exit 1
onbb_echo_result_of_start_success